import React, { createContext, useContext, useState, useEffect } from "react";
import Cookies from "js-cookie";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  hi: {
    home: "होम",
    latest: "ताज़ा खबरें",
    categories: "श्रेणियाँ",
    search: "खोजें",
    searchPlaceholder: "खबरें खोजें...",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    share: "शेयर करें",
    views: "व्यूज",
    readMore: "पूरी खबर पढ़ें",
    noResults: "कोई खबर नहीं मिली",
    allNews: "सभी खबरें",
    breakingNews: "बड़ी खबर",
    relatedNews: "संबंधित खबरें",
    followUs: "हमें फॉलो करें",
    copyright: "सर्वाधिकार सुरक्षित",
    backToHome: "होम पर वापस जाएं",
    bihar: "बिहार",
    jharkhand: "झारखंड",
    national: "देश",
    international: "दुनिया",
    sports: "खेल",
    entertainment: "मनोरंजन",
    politics: "राजनीति",
    business: "बिज़नेस",
    technology: "टेक",
    education: "शिक्षा",
    health: "स्वास्थ्य",
    crime: "अपराध",
    religion: "धर्म",
    lifestyle: "लाइफस्टाइल",
    webstories: "वेब स्टोरीज़",
    videos: "वीडियो",
    photos: "फोटो",
    trending: "ट्रेंडिंग",
    live: "लाइव",
    opinion: "ओपिनियन",
    special: "स्पेशल",
    weather: "मौसम",
    astrology: "ज्योतिष",
    career: "करियर",
    auto: "ऑटो",
    gadgets: "गैजेट्स",
    socialMedia: "सोशल मीडिया",
    factCheck: "फैक्ट चेक",
    agriculture: "कृषि",
    environment: "पर्यावरण",
    science: "विज्ञान",
    history: "इतिहास",
    literature: "साहित्य",
    cinema: "सिनेमा",
    music: "संगीत",
    travel: "ट्रैवल",
    food: "फूड",
    fashion: "फैशन",
    women: "महिलाएं",
    kids: "बच्चे",
    youth: "युवा",
    elderly: "बुजुर्ग",
    others: "अन्य",
    // Admin
    postsDashboard: "पोस्ट डैशबोर्ड",
    newPost: "नई पोस्ट लिखें",
    editPost: "पोस्ट एडिट करें",
    deletePost: "पोस्ट डिलीट करें",
    viewPost: "पोस्ट देखें",
    published: "प्रकाशित",
    draft: "ड्राफ्ट",
    scheduled: "शेड्यूल्ड",
    publish: "प्रकाशित करें",
    update: "अपडेट करें",
    saveAsDraft: "ड्राफ्ट में सेव करें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    yes: "हाँ",
    no: "नहीं",
    title: "शीर्षक",
    content: "सामग्री",
    category: "श्रेणी",
    tags: "टैग",
    image: "इमेज",
    video: "वीडियो",
    status: "स्टेटस",
    date: "दिनांक",
    author: "लेखक",
    actions: "कार्रवाई",
    edit: "एडिट",
    delete: "डिलीट",
    save: "सेव",
    loading: "लोड हो रहा है...",
    success: "सफलता",
    error: "त्रुटि",
    message: "संदेश",
    submit: "सबमिट",
    required: "अनिवार्य",
    invalid: "अमान्य",
    alreadyExists: "पहले से मौजूद है",
    notFound: "नहीं मिला",
    accessDenied: "एक्सेस वर्जित",
    login: "लॉगिन",
    logout: "लॉगआउट",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    users: "यूज़र्स",
    comments: "कमेंट्स",
    reports: "रिपोर्ट्स",
    notifications: "नोटिफिकेशन्स",
    dashboard: "डैशबोर्ड",
    analytics: "एनालिटिक्स",
    media: "मीडिया",
    upload: "अपलोड",
    download: "डाउनलोड",
    preview: "प्रीव्यू",
    searchUser: "यूज़र खोजें",
    searchPost: "पोस्ट खोजें",
    searchCategory: "श्रेणी खोजें",
    searchTag: "टैग खोजें",
    filter: "फ़िल्टर",
    sortBy: "सॉर्ट करें",
    noComments: "कोई कमेंट नहीं",
    addComment: "कमेंट जोड़ें",
    reply: "जवाब दें",
    postedOn: "को पोस्ट किया गया",
    publishedOn: "को प्रकाशित किया गया",
    updatedOn: "को अपडेट किया गया",
    readTime: "पढ़ने का समय",
    minutes: "मिनट",
    words: "शब्द",
    shareOn: "पर शेयर करें",
    copied: "कॉपी किया गया",
    copyLink: "लिंक कॉपी करें",
    more: "अधिक",
    less: "कम",
    topStories: "टॉप स्टोरीज़",
    mustRead: "ज़रूर पढ़ें",
    breaking: "ब्रेकिंग",
    exclusive: "एक्सक्लूसिव",
    interviews: "इंटरव्यू",
    groundReport: "ग्राउंड रिपोर्ट",
    states: "राज्य",
    stateBR: "बिहार",
    stateJH: "झारखंड",
    stateUP: "उत्तर प्रदेश",
    stateMP: "मध्य प्रदेश",
    stateRJ: "राजस्थान",
    stateHR: "हरियाणा",
    statePB: "पंजाब",
    stateHP: "हिमाचल प्रदेश",
    stateUK: "उत्तराखंड",
    stateDL: "दिल्ली",
    stateCH: "चंडीगढ़",
    stateJK: "जम्मू और कश्मीर",
    stateLA: "लद्दाख",
    stateAS: "असम",
    loginToContinue: "जारी रखने के लिए लॉगिन करें",
    postsCountDescription: "पोस्ट — सिर्फ आप इन्हें एडिट या डिलीट कर सकते हैं",
    total: "कुल",
    adminPanelTitle: "⚙️ एडमिन पैनल",
    viewSite: "साइट देखें",
    newPostTitle: "नई पोस्ट",
    location: "स्थान",
    dateLabel: "तारीख",
    headlines: "मुख्य समाचार",
    detailedReport: "विस्तृत रिपोर्ट",
    isRequired: "जरूरी है",
    uploadImage: "फोटो अपलोड करें",
    selectStatePrompt: "राज्य चुनें",
    dashboardTitle: "डैशबोर्ड",
  },
  en: {
    home: "Home",
    latest: "Latest News",
    categories: "Categories",
    search: "Search",
    searchPlaceholder: "Search news...",
    about: "About Us",
    contact: "Contact Us",
    share: "Share",
    views: "Views",
    readMore: "Read Full Story",
    noResults: "No news found",
    allNews: "All News",
    breakingNews: "Breaking News",
    relatedNews: "Related News",
    followUs: "Follow Us",
    copyright: "All Rights Reserved",
    backToHome: "Back to Home",
    bihar: "Bihar",
    jharkhand: "Jharkhand",
    national: "National",
    international: "International",
    sports: "Sports",
    entertainment: "Entertainment",
    politics: "Politics",
    business: "Business",
    technology: "Tech",
    education: "Education",
    health: "Health",
    crime: "Crime",
    religion: "Religion",
    lifestyle: "Lifestyle",
    webstories: "Web Stories",
    videos: "Videos",
    photos: "Photos",
    trending: "Trending",
    live: "Live",
    opinion: "Opinion",
    special: "Special",
    weather: "Weather",
    astrology: "Astrology",
    career: "Career",
    auto: "Auto",
    gadgets: "Gadgets",
    socialMedia: "Social Media",
    factCheck: "Fact Check",
    agriculture: "Agriculture",
    environment: "Environment",
    science: "Science",
    history: "History",
    literature: "Literature",
    cinema: "Cinema",
    music: "Music",
    travel: "Travel",
    food: "Food",
    fashion: "Fashion",
    women: "Women",
    kids: "Kids",
    youth: "Youth",
    elderly: "Elderly",
    others: "Others",
    // Admin
    postsDashboard: "Posts Dashboard",
    newPost: "New Post",
    editPost: "Edit Post",
    deletePost: "Delete Post",
    viewPost: "View Post",
    published: "Published",
    draft: "Draft",
    scheduled: "Scheduled",
    publish: "Publish",
    update: "Update",
    saveAsDraft: "Save as Draft",
    cancel: "Cancel",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    title: "Title",
    content: "Content",
    category: "Category",
    tags: "Tags",
    image: "Image",
    video: "Video",
    status: "Status",
    date: "Date",
    author: "Author",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    message: "Message",
    submit: "Submit",
    required: "Required",
    invalid: "Invalid",
    alreadyExists: "Already exists",
    notFound: "Not found",
    accessDenied: "Access denied",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    settings: "Settings",
    users: "Users",
    comments: "Comments",
    reports: "Reports",
    notifications: "Notifications",
    dashboard: "Dashboard",
    analytics: "Analytics",
    media: "Media",
    upload: "Upload",
    download: "Download",
    preview: "Preview",
    searchUser: "Search User",
    searchPost: "Search Post",
    searchCategory: "Search Category",
    searchTag: "Search Tag",
    filter: "Filter",
    sortBy: "Sort by",
    noComments: "No comments yet",
    addComment: "Add Comment",
    reply: "Reply",
    postedOn: "Posted on",
    publishedOn: "Published on",
    updatedOn: "Updated on",
    readTime: "Read time",
    minutes: "min",
    words: "words",
    shareOn: "Share on",
    copied: "Copied!",
    copyLink: "Copy Link",
    more: "More",
    less: "Less",
    topStories: "Top Stories",
    mustRead: "Must Read",
    breaking: "Breaking",
    exclusive: "Exclusive",
    interviews: "Interviews",
    groundReport: "Ground Report",
    states: "States",
    stateBR: "Bihar",
    stateJH: "Jharkhand",
    stateUP: "Uttar Pradesh",
    stateMP: "Madhya Pradesh",
    stateRJ: "Rajasthan",
    stateHR: "Haryana",
    statePB: "Punjab",
    stateHP: "Himachal Pradesh",
    stateUK: "Uttarakhand",
    stateDL: "Delhi",
    stateCH: "Chandigarh",
    stateJK: "Jammu & Kashmir",
    stateLA: "Ladakh",
    stateAS: "Assam",
    loginToContinue: "Login to continue",
    postsCountDescription: "posts — only you can edit or delete them",
    total: "total",
    adminPanelTitle: "⚙️ Admin Panel",
    viewSite: "View Site",
    newPostTitle: "New Post",
    location: "Location",
    dateLabel: "Date",
    headlines: "News Headlines",
    detailedReport: "Detailed News Report",
    isRequired: "is required",
    uploadImage: "Featured image is required",
    selectStatePrompt: "Select State",
    dashboardTitle: "Dashboard",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("hi");

  useEffect(() => {
    const savedLang = Cookies.get("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "hi")) {
      setLanguageState(savedLang);
    } else {
      // Default to Hindi
      Cookies.set("language", "hi", { expires: 365 });
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    Cookies.set("language", lang, { expires: 365 });
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
