"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "hi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  mounted: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  hi: {
    home: "होम",
    bihar: "बिहार",
    jharkhand: "झारखंड",
    politics: "राजनीति",
    entertainment: "मनोरंजन",
    sports: "खेल",
    crime: "क्राइम",
    business: "व्यापार",
    education: "शिक्षा",
    health: "स्वास्थ्य",
    national: "राष्ट्रीय",
    international: "अंतरराष्ट्रीय",
    other: "अन्य",
    patna: "पटना",
    ranchi: "रांची",
    login: "लॉगिन",
    adminPanel: "एडमिन पैनल",
    signOut: "साइन आउट",
    selectLanguage: "भाषा चुनें",
    hindi: "हिन्दी",
    english: "English",
    heroTitle: "बिहार-झारखंड की",
    heroSubtitle: "सबसे तेज खबरें",
    heroDesc: "हर पल, हर घटना, हर खबर — STV News पर सबसे पहले। आप को रखे आगे।",
    liveBreaking: "Live · ब्रेकिंग न्यूज़",
    latestNews: "ताजा खबरें",
    categories: "श्रेणियाँ",
    quickLinks: "क्विक लिंक्स",
    contactUs: "हमसे संपर्क करें",
    followUs: "हमें फॉलो करें",
    date: "तारीख",
    aboutStv: "STV News बिहार और झारखंड का नंबर 1 डिजिटल न्यूज़ चैनल है।",
    chooseLanguage: "भाषा चुनें",
    adminBadge: "एडमिन खाता",
    adminSection: "एडमिन सेक्शन",
    createPost: "नई खबर लिखें",
    editPost: "खबर संपादित करें",
    dashboard: "डैशबोर्ड",
    postsDashboard: "पोस्ट डैशबोर्ड",
    newPost: "नई पोस्ट",
    totalPosts: "कुल पोस्ट",
    totalLikes: "कुल लाइक",
    totalViews: "कुल व्यूज",
    comments: "कमेंट",
    allPosts: "सभी पोस्ट",
    actions: "एक्शन",
    edit: "एडिट",
    delete: "डिलीट",
    noPosts: "कोई पोस्ट नहीं है।",
    createFirst: "पहली पोस्ट लिखें!",
    title: "शीर्षक",
    content: "खबर की सामग्री",
    category: "श्रेणी",
    selectCategory: "श्रेणी चुनें",
    newCategory: "नई श्रेणी",
    createCategory: "नई श्रेणी बनाएं",
    tags: "टैग्स",
    tagPlaceholder: "टैग लिखें और Enter दबाएं...",
    tagHelp: "Enter या comma (,) दबाकर टैग जोड़ें",
    imageVideo: "फोटो / वीडियो",
    publishNow: "अभी पब्लिश करें",
    saveDraft: "ड्राफ्ट सेव करें",
    schedule: "शेड्यूल करें",
    locationAndTime: "स्थान और समय",
    city: "शहर",
    state: "राज्य",
    selectState: "राज्य चुनें",
    eventDate: "घटना तारीख",
    eventTime: "घटना समय",
    optional: "(वैकल्पिक)",
    allSet: "सब कुछ तैयार है — पब्लिश कर सकते हैं!",
    requiredFields: "शीर्षक, सामग्री, श्रेणी और फोटो जरूरी हैं",
    saving: "सेव हो रहा है...",
    done: "हो गया!",
    publishDate: "पब्लिश डेट और टाइम",
    draftSaved: "ड्राफ्ट सेव हुआ!",
    postScheduled: "पोस्ट शेड्यूल हो गई!",
    postPublished: "पोस्ट पब्लिश हो गई! 🎉",
    errorOccurred: "कुछ गड़बड़ हुई, दोबारा कोशिश करें",
    published: "प्रकाशित",
    draft: "ड्राफ्ट",
    scheduled: "शेड्यूल",
    deletePostConfirm: "पोस्ट डिलीट करें?",
    permanentAction: "यह काम वापस नहीं होगा।",
    yesDelete: "हाँ, डिलीट करें",
    deleting: "हटा रहे हैं...",
    postDeleted: "पोस्ट डिलीट हो गई ✓",
    deleteFailed: "डिलीट नहीं हुई, फिर कोशिश करें",
    viewPost: "पोस्ट देखें",
    deletePost: "डिलीट करें",
    chars: "अक्षर",
    cancel: "रद्द करें",
    add: "जोड़ें",
    titlePlaceholder: "खबर का मुख्य शीर्षक यहाँ लिखें...",
    contentPlaceholder: "पूरी खबर विस्तार से यहाँ लिखें...",
    updatePost: "अपडेट करें",
    publishPost: "पब्लिश करें",
    stvNews: "STV News बिहार झारखंड",
    followForLatest: "ताजा समाचार पढ़ने के लिए STV News को फॉलो करें",
    breakingNewsSub: "Breaking News: देश-विदेश की हर बड़ी खबर यहाँ मिलेगी",
    allNews: "सभी खबरें",
    views: "व्यूज",
    share: "शेयर",
    like: "लाइक",
    noPostsFound: "कोई खबर नहीं मिली।",
    trendingNews: "ट्रेंडिंग खबरें",
    trendingComingSoon: "ट्रेंडिंग खबरें जल्द आएंगी",
    popularTags: "लोकप्रिय टैग",
    relatedNews: "से जुड़ी खबरें",
    newsFound: "खबरें मिलीं",
    noRelatedNews: "से जुड़ी कोई खबर नहीं",
    searchResults: "खोज परिणाम",
    searchPlaceholder: "खबर खोजें...",
    stateUP: "उत्तर प्रदेश",
    stateDelhi: "दिल्ली",
    stateWB: "पश्चिम बंगाल",
    stateMH: "महाराष्ट्र",
    stateMP: "मध्य प्रदेश",
    stateRJ: "राजस्थान",
    stateGJ: "गुजरात",
    statePB: "पंजाब",
    stateHR: "हरियाणा",
    stateOD: "ओडिशा",
    stateCH: "छत्तीसगढ़",
    stateUK: "उत्तराखंड",
    stateAS: "असम",
    loginToContinue: "जारी रखने के लिए लॉगिन करें",
    postsCountDescription: "पोस्ट — सिर्फ आप इन्हें एडिट या डिलीट कर सकते हैं",
    total: "कुल",
  },
  en: {
    home: "Home",
    bihar: "Bihar",
    jharkhand: "Jharkhand",
    politics: "Politics",
    entertainment: "Entertainment",
    sports: "Sports",
    crime: "Crime",
    business: "Business",
    education: "Education",
    health: "Health",
    national: "National",
    international: "International",
    other: "Other",
    patna: "Patna",
    ranchi: "Ranchi",
    login: "Login",
    adminPanel: "Admin Panel",
    signOut: "Sign Out",
    selectLanguage: "Select Language",
    hindi: "Hindi",
    english: "English",
    heroTitle: "Bihar-Jharkhand's",
    heroSubtitle: "Fastest News",
    heroDesc: "Every moment, every event, every story — first on STV News. Keeping you ahead.",
    liveBreaking: "Live · Breaking News",
    latestNews: "Latest News",
    categories: "Categories",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    followUs: "Follow Us",
    date: "Date",
    aboutStv: "STV News is the #1 digital news channel for Bihar and Jharkhand.",
    chooseLanguage: "Choose Language",
    adminBadge: "Admin Account",
    adminSection: "Admin Section",
    createPost: "Create New Article",
    editPost: "Edit Article",
    dashboard: "Dashboard",
    postsDashboard: "Posts Dashboard",
    newPost: "New Post",
    totalPosts: "Total Posts",
    totalLikes: "Total Likes",
    totalViews: "Total Views",
    comments: "Comments",
    allPosts: "All Posts",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    noPosts: "No posts yet.",
    createFirst: "Create the first one!",
    title: "Title",
    content: "Article Content",
    category: "Category",
    selectCategory: "Select Category",
    newCategory: "New Category",
    createCategory: "Create New Category",
    tags: "Tags",
    tagPlaceholder: "Write tags and press Enter...",
    tagHelp: "Add tags by pressing Enter or comma (,)",
    imageVideo: "Image / Video",
    publishNow: "Publish Now",
    saveDraft: "Save Draft",
    schedule: "Schedule",
    locationAndTime: "Location & Time",
    city: "City",
    state: "State",
    selectState: "Select State",
    eventDate: "Event Date",
    eventTime: "Event Time",
    optional: "(Optional)",
    allSet: "All set — ready to publish!",
    requiredFields: "Title, content, category & image are required",
    saving: "Saving...",
    done: "Done!",
    publishDate: "Publish Date & Time",
    draftSaved: "Draft saved!",
    postScheduled: "Post scheduled!",
    postPublished: "Article published! 🎉",
    errorOccurred: "Something went wrong. Please try again.",
    published: "Published",
    draft: "Draft",
    scheduled: "Scheduled",
    deletePostConfirm: "Delete this post?",
    permanentAction: "This action cannot be undone.",
    yesDelete: "Yes, Delete",
    deleting: "Deleting...",
    postDeleted: "Post deleted ✓",
    deleteFailed: "Delete failed, try again",
    viewPost: "View post",
    deletePost: "Delete post",
    chars: "chars",
    cancel: "Cancel",
    add: "Add",
    titlePlaceholder: "Write the main title of the article here...",
    contentPlaceholder: "Write the full article content in detail here...",
    updatePost: "Update Post",
    publishPost: "Publish Post",
    stvNews: "STV News Bihar Jharkhand",
    followForLatest: "Follow STV News for latest updates",
    breakingNewsSub: "Breaking News: Get every big story here",
    allNews: "All News",
    views: "Views",
    share: "Share",
    like: "Like",
    noPostsFound: "No news found.",
    trendingNews: "Trending News",
    trendingComingSoon: "Trending news coming soon",
    popularTags: "Popular Tags",
    relatedNews: "related news",
    newsFound: "articles found",
    noRelatedNews: "No news found for",
    searchResults: "Search Results",
    searchPlaceholder: "Search news...",
    stateUP: "Uttar Pradesh",
    stateDelhi: "Delhi",
    stateWB: "West Bengal",
    stateMH: "Maharashtra",
    stateMP: "Madhya Pradesh",
    stateRJ: "Rajasthan",
    stateGJ: "Gujarat",
    statePB: "Punjab",
    stateHR: "Haryana",
    stateOD: "Odisha",
    stateCH: "Chhattisgarh",
    stateUK: "Uttarakhand",
    stateAS: "Assam",
    loginToContinue: "Login to continue",
    postsCountDescription: "posts — only you can edit or delete them",
    total: "total",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("hi");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "hi" || savedLang === "en")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    // Set cookie for server-side rendering awareness (ISR pages read this)
    document.cookie = `language=${lang}; path=/; max-age=31536000`;
  };

  const t = (key: string): string => {
    // During hydration, always return hindi to match server render
    if (!mounted) return translations["hi"][key] ?? key;
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, mounted }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
